services:
  - type: web
    name: SHOP
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn SHOP coffee.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "your-secret-key"
      - key: ALLOWED_HOSTS
        value: "your-app-name.onrender.com"