# Generated by Django 5.1.4 on 2024-12-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Pytho',
            new_name='photo',
        ),
    ]
