# Generated by Django 5.1.4 on 2024-12-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_pytho_product_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-publish_date']},
        ),
    ]
